### ISSUE TITLE
请多多指教

### ISSUE THREAD

**Issue by qingsong-xu** [peng8/react-native-checkbox#1]
其实我很好奇，点击后checkSelect这个方法定义在前端，是怎样去使得被选中的那一行样式和别的不同的，因为数据是放在了listView里去渲染的。 有可能的话，还麻烦给一下你博客里的完整代码地址，我下载来看看，学习一下，谢谢~
checkSelect(checked,id){
  console.log(checked+",,,,"+id);
         
}

**Comment by peng8** [comment]
checkbox  本身也是组件，listview 相当于是父组件，checkbox状态的维护改变 是调用了子组件里的方法
，这里的checkSelect只是回调函数而已，实际上在执行这个回调函数前，子组件内部的state已经发生变化了
